# Day 1 solutions

In [ ]:
# Solution 1

RAINBOW

In [1]:
# Solution 2

print("LETS UPGRADE")

LETS UPGRADE


In [8]:
# Solution 3

#Case 1- when cost price is less than selling price

cost_price = int(input())
selling_price = int(input())
if selling_price > cost_price:
    print("Profit")
elif selling_price < cost_price:
    print("Loss")
else:
    print("Neither")

20
30
Profit


In [9]:
# Solution 3

#Case 2- when cost price is more than selling price

cost_price = int(input())
selling_price = int(input())
if selling_price > cost_price:
    print("Profit")
elif selling_price < cost_price:
    print("Loss")
else:
    print("Neither")

40
25
Loss


In [12]:
# Solution 3

#Case 2- when cost price is equal to selling price

cost_price = int(input())
selling_price = int(input())
if selling_price > cost_price:
    print("Profit")
elif selling_price < cost_price:
    print("Loss")
else:
    print("Neither")

50
50
Neither


In [17]:
# Solution 4

# Example- when input is 20 euros and output is 1600

Euros_1 = 80
Euros = int(input())
print(Euros_1*Euros)

20
1600


# Day 2 solutions

In [31]:
# Solution 1

l = []
for i in range(0,10,2):
    l.append(i)
print(l)

[0, 2, 4, 6, 8]


In [35]:
# Solution 2

# Using a list comprehension, create a new list called "new" out of the list "num", which contains only the positive numbers from the list, as integers

num = [100, -250, 3.5, -19.7, -33.2, 47, 58, -25, -600, 245]
new = [int(x) for x in num if x > 0]
print(new)

[100, 3, 47, 58, 245]


In [36]:
# Solution 3

n = int(input("Enter the number "))
d = {}
for x in range(1, 1+n):
    d[x] = x*x
print(d)

Enter the number 5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [ ]:
#Solution 4



# Day 3 solutions

In [42]:
# Solution 1

# Creating an array from 2 to 50 with step size of 3.

import numpy as np
num_1 = np.arange(2,50,3)
print(num_1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [18]:
# Solution 2

# Converting 2 list to 1D array and Concatenating and sorting them.

import numpy as np
List_1 = [10,15,22,13,4]
List_2 = [25,66,72,18,100]
Array_1 = np.array(List_1)
Array_2 = np.array(List_2)
con = np.concatenate((Array_1, Array_2))
print(con)
print(np.sort(con))

[ 10  15  22  13   4  25  66  72  18 100]
[  4  10  13  15  18  22  25  66  72 100]


In [23]:
# Solution 3

# Finding dimension and size of ndarray.

import numpy as np
array = np.arange(5)
print(array)
print(array.ndim)
print(array.size)

[0 1 2 3 4]
1
5


In [27]:
# Solution 4

# Converting 1D array into a 2D array.

import numpy as np
array_1D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_2D = array_1D.reshape(4,3)
print(array_2D)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
# Solution 5

# Stacking 2 square numpy arrays vertically and horizontally.
#Case 1- Vertically

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a_1 = a.reshape(2,2)
b_1 = b.reshape(2,2)
vertical = np.vstack((a_1,b_1))
print(vertical)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
# Solution 5

# Stacking 2 square numpy arrays vertically and horizontally.
#Case 2- Horizontally

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a_1 = a.reshape(2,2)
b_1 = b.reshape(2,2)
horizontal = np.hstack((a_1,b_1))
print(horizontal)

[[1 2 5 6]
 [3 4 7 8]]


In [44]:
# Solution 6

# Checking unique value and it's count.

import numpy as np
a = np.array([1,2,2,3,5,6,9,5,3,2,1])
unique, counts = np.unique(a, return_counts=True)
print(np.asarray((unique,counts)).T)

[[1 2]
 [2 3]
 [3 2]
 [5 2]
 [6 1]
 [9 1]]


# Day 4 solutions

In [5]:
# Solution 1

# Importing pandas and cheking it's version.

import pandas as pd
print(pd.__version__)

1.0.5


In [3]:
# Solution 2

# Creating numpy array and converting it into pandas series.

import numpy as np
import pandas as pd
array = np.array([123, 456, 789, 564])
print(array)
series = pd.Series(array)
print(series)

[123 456 789 564]
0    123
1    456
2    789
3    564
dtype: int32


In [5]:
# Solution 3

# Converting index to column in a dataframe.

import pandas as pd
data = {'Product': ['Computer', 'Washing Machine', 'Television', 'Air Conditioner', 'Mobile'],
       'Price': ['15000', '8000', '25000', '30000', '10000']}
df = pd.DataFrame(data,columns= ['Product', 'Price'], index = ['Item_1', 'Item_2', 'Item_3', 'Item_4', 'Item_5'])
df.reset_index(inplace=True)
print(df)

    index          Product  Price
0  Item_1         Computer  15000
1  Item_2  Washing Machine   8000
2  Item_3       Television  25000
3  Item_4  Air Conditioner  30000
4  Item_5           Mobile  10000


In [6]:
# Solution 4

#List of all datasets available in seaborn and loading mpg dataset.
# Listing all datasets.

import seaborn as sns
list= sns.get_dataset_names()
print(list)

C:\Users\user\anaconda3\lib\site-packages\seaborn\utils.py:384: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 384 of the file C:\Users\user\anaconda3\lib\site-packages\seaborn\utils.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  gh_list = BeautifulSoup(http)


['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'exercise', 'flights', 'fmri', 'gammas', 'geyser', 'iris', 'mpg', 'penguins', 'planets', 'tips', 'titanic']


In [4]:
# Loading mpg dataset

mpg = sns.load_dataset('mpg')

In [5]:
mpg

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa          buick skylark 320  
2            70     usa         plymouth satellite  
3            70     usa              amc rebel sst  
4            70     usa                ford torino  
..          ...     ...                        ...  
393          82     usa            ford mustang gl  
394          82  europe                  vw pickup  
395          82     usa              dodge rampage  
396          82     usa                ford ranger  
397          82     usa                 chevy s-10  

[398 rows x 9 columns]

In [8]:
# Solution 5

# Origin of cars countrywise.

mpg['origin'].unique()

array(['usa', 'japan', 'europe'], dtype=object)

In [9]:
# Solution 6

# Cars belonging to USA.

import pandas as pd
mpg['origin'].value_counts()

usa       249
japan      79
europe     70
Name: origin, dtype: int64