# Day 1 solutions

In [ ]:
# Solution 1

RAINBOW

In [1]:
# Solution 2

print("LETS UPGRADE")

LETS UPGRADE


In [8]:
# Solution 3

#Case 1- when cost price is less than selling price

cost_price = int(input())
selling_price = int(input())
if selling_price > cost_price:
    print("Profit")
elif selling_price < cost_price:
    print("Loss")
else:
    print("Neither")

20
30
Profit


In [9]:
# Solution 3

#Case 2- when cost price is more than selling price

cost_price = int(input())
selling_price = int(input())
if selling_price > cost_price:
    print("Profit")
elif selling_price < cost_price:
    print("Loss")
else:
    print("Neither")

40
25
Loss


In [12]:
# Solution 3

#Case 2- when cost price is equal to selling price

cost_price = int(input())
selling_price = int(input())
if selling_price > cost_price:
    print("Profit")
elif selling_price < cost_price:
    print("Loss")
else:
    print("Neither")

50
50
Neither


In [17]:
# Solution 4

# Example- when input is 20 euros and output is 1600

Euros_1 = 80
Euros = int(input())
print(Euros_1*Euros)

20
1600


# Day 2 solutions

In [31]:
# Solution 1

l = []
for i in range(0,10,2):
    l.append(i)
print(l)

[0, 2, 4, 6, 8]


In [35]:
# Solution 2

# Using a list comprehension, create a new list called "new" out of the list "num", which contains only the positive numbers from the list, as integers

num = [100, -250, 3.5, -19.7, -33.2, 47, 58, -25, -600, 245]
new = [int(x) for x in num if x > 0]
print(new)

[100, 3, 47, 58, 245]


In [36]:
# Solution 3

n = int(input("Enter the number "))
d = {}
for x in range(1, 1+n):
    d[x] = x*x
print(d)

Enter the number 5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [ ]:
#Solution 4



# Day 3 solutions

In [42]:
# Solution 1

# Creating an array from 2 to 50 with step size of 3.

import numpy as np
num_1 = np.arange(2,50,3)
print(num_1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [18]:
# Solution 2

# Converting 2 list to 1D array and Concatenating and sorting them.

import numpy as np
List_1 = [10,15,22,13,4]
List_2 = [25,66,72,18,100]
Array_1 = np.array(List_1)
Array_2 = np.array(List_2)
con = np.concatenate((Array_1, Array_2))
print(con)
print(np.sort(con))

[ 10  15  22  13   4  25  66  72  18 100]
[  4  10  13  15  18  22  25  66  72 100]


In [23]:
# Solution 3

# Finding dimension and size of ndarray.

import numpy as np
array = np.arange(5)
print(array)
print(array.ndim)
print(array.size)

[0 1 2 3 4]
1
5


In [27]:
# Solution 4

# Converting 1D array into a 2D array.

import numpy as np
array_1D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_2D = array_1D.reshape(4,3)
print(array_2D)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
# Solution 5

# Stacking 2 square numpy arrays vertically and horizontally.
#Case 1- Vertically

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a_1 = a.reshape(2,2)
b_1 = b.reshape(2,2)
vertical = np.vstack((a_1,b_1))
print(vertical)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
# Solution 5

# Stacking 2 square numpy arrays vertically and horizontally.
#Case 2- Horizontally

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a_1 = a.reshape(2,2)
b_1 = b.reshape(2,2)
horizontal = np.hstack((a_1,b_1))
print(horizontal)

[[1 2 5 6]
 [3 4 7 8]]


In [44]:
# Solution 6

# Checking unique value and it's count.

import numpy as np
a = np.array([1,2,2,3,5,6,9,5,3,2,1])
unique, counts = np.unique(a, return_counts=True)
print(np.asarray((unique,counts)).T)

[[1 2]
 [2 3]
 [3 2]
 [5 2]
 [6 1]
 [9 1]]
